{
 "title": "SmartGreenHouse",
 "time": { "from": "2022-07-23T22:31:43.978Z", "to": "2022-07-25T09:27:47.562Z" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Activation of the lighting system ",
   "type": "status-history",
   "description": "for each day",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "\nselect avg(sample) as \" activation \", minute(timestamp) as \"time\" \nfrom light \nwhere  sample<20 and DAY(timestamp)=DAY(current_date())and month(timestamp)=month(current_date())and year(timestamp)=year(current_date())\ngroup by minute(timestamp);\n"
    }
   ]
  },
  {
   "title": "Activation of the ventilation system ",
   "type": "status-history",
   "description": "for each day",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\nselect avg(sample) as \" activation \", minute(timestamp) as \"time\" \nfrom temperature \nwhere  sample>26 and DAY(timestamp)=DAY(current_date())and month(timestamp)=month(current_date())and year(timestamp)=year(current_date())\ngroup by minute(timestamp);\n"
    }
   ]
  },
  {
   "title": "Water used in last month",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum((60-sample)*0.3) as Litri\nfrom humidity as prima \nwhere \nsample<40 \nand\nMONTH(timestamp)=MONTH(current_date())\nand \nYEAR(timestamp)=YEAR(current_date())\nand\nDATE_ADD(timestamp, interval 10 SECOND) IN ( select timestamp\n                                             from humidity\n                                             where machineid=prima.machineid \n                                             and \n                                             sample>=60 \n                                             )\n"
    }
   ]
  },
  {
   "title": "GreenHouse_N1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM temperature\nWHERE\n  machineid = 1\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Light",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM light\nWHERE\n  machineid = 1\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM humidity\nWHERE\n  machineid = 1\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Humidty",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM humidity\nWHERE\n  machineid = 1\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM temperature\nWHERE\n  machineid = 1\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Light",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM light\nWHERE\n  machineid = 1\nORDER BY timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "GreenHouse_N2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM temperature\nWHERE\n  machineid = 2\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Light",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM light\nWHERE\n  machineid = 2\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM humidity\nWHERE\n  machineid = 2\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Humidty",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM humidity\nWHERE\n  machineid = 2\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM temperature\nWHERE\n  machineid = 2\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Light",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM light\nWHERE\n  machineid = 2\nORDER BY timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "GreenHouse_N3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM temperature\nWHERE\n  machineid = 3\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Light",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM light\nWHERE\n  machineid = 3\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM humidity\nWHERE\n  machineid = 3\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Humidty",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM humidity\nWHERE\n  machineid = 3\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM temperature\nWHERE\n  machineid = 3\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Light",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM light\nWHERE\n  machineid = 3\nORDER BY timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "GreenHouse_N4",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM temperature\nWHERE\n  machineid = 4\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Light",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM light\nWHERE\n  machineid = 4\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM humidity\nWHERE\n  machineid = 4\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Humidty",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM humidity\nWHERE\n  machineid = 4\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM temperature\nWHERE\n  machineid = 4\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Light",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM light\nWHERE\n  machineid = 4\nORDER BY timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "GreenHouse_N5",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM temperature\nWHERE\n  machineid = 5\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Light",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM light\nWHERE\n  machineid = 5\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM humidity\nWHERE\n  machineid = 5\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Humidty",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM humidity\nWHERE\n  machineid = 5\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM temperature\nWHERE\n  machineid = 5\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Light",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM light\nWHERE\n  machineid = 3\nORDER BY timestamp"
      }
     ]
    }
   ]
  }
 ]
}